export interface Empleado {
  // Generales
  id: null;
  no: number;
  userReg: String;
  userMod: String;
  // Entidad
  nomb: String;
  nacio: String;
  apell: String;
  telef: String;
  pass: String;
  cedu: String;
  sex: String;
  stat: String;
  emp: String;
  puest: String;
  ars: String;
  suc: String;
  otrsIngs: String;
  finVac: Date;
  iniVac: Date;
  noDepe: Number;
  turn: String;
  cod: String;
  dpto: String;
  fechaNac: Date;
  fechaCont: Date;
  salario: Number;
  cuenta: String;
  edad: Number;
  acciones: [Object];
  notas: String;
  supervisor: String;
  direccion: String;
}
